In [2]:
#numpyの使い方 
import numpy as np

In [54]:
#配列の生成
a=np.array([0,1,2,3,4,5]) 
a_list=([0,1,2,3,4,5])    #np.arrayをつけないと　ただのlistと認識されてしまう
print(type(a))
print(type(a_list))

<class 'numpy.ndarray'>
<class 'list'>


In [7]:
a=np.arange(6)

In [13]:
#配列の形を変更 .reshape( , )
a=np.arange(6)
b=a.reshape(2,3)

print(a)
print(b)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [16]:
#配列の形を返す .shape
print(a.shape)
print(b.shape)

#配列のサイズを返す .size
print(a.size)
print(b.size)


(6,)
(2, 3)
6
6


In [20]:
nrow,ncol=b.shape
print(nrow,ncol)

2 3


In [56]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [59]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [60]:
#配列の要素をシャフル permutation()
np.random.permutation(range(6))

array([1, 0, 5, 2, 4, 3])

In [61]:
#省略型 range()は省略できる
np.random.permutation(6)

array([2, 0, 5, 4, 3, 1])

In [73]:
#配列の連結
a=np.array([0,1,2,3,4,5])
a=a.reshape(2,3)
b=np.array([6,7,8,9,10,11])
b=b.reshape(2,3)
print("a=",a)
print("b=",b)

#配列を右（水平）に連結 hstack([ , ])
#配列を下（垂直）に連結 vstack([ , ])

c=np.hstack([a,b])
d=np.vstack([a,b])

print("hstack:",c)
print("vstack:",d)

a= [[0 1 2]
 [3 4 5]]
b= [[ 6  7  8]
 [ 9 10 11]]
hstack: [[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]
vstack: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [80]:
#配列の加工
a=np.array([0,1,2,3,4,5,6,7,8,9,10,11])
a=a.reshape(3,4)
print(a)

#2行目を取り除く＝必要な行だけを取り出す
b=a[[0,2],:] # [[取り出したい行],他は捨てる]　という意味
print(b)

#３列目を取り除く＝必要な列だけを取り出す
c=a[:,[0,1,3]]
print(c)

#条件にあった要素を置き換える
a[a%2==0]=-1 #２で割れる配列番号の要素だけに-1を代入する
print(a)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 8  9 10 11]]
[[ 0  1  3]
 [ 4  5  7]
 [ 8  9 11]]
[[-1  1 -1  3]
 [-1  5 -1  7]
 [-1  9 -1 11]]


In [91]:
#演算
a=np.array([1,2,3,4,5,6])
a=a.reshape(2,3)
print(a)
print(a+1)
print(np.sum(a))
print(np.mean(a))

#軸（行または列）を固定して演算（２次元の場合）　axis=
print(np.sum(a,axis=0))#列ごとの和
print(np.sum(a,axis=1))#行ごとの和

[[1 2 3]
 [4 5 6]]
[[2 3 4]
 [5 6 7]]
21
3.5
[5 7 9]
[ 6 15]


In [92]:
#ベクトルの積
a=np.array([0,1,2,3])
b=np.array([4,5,6,7])

print(a.dot(b)) #ベクトルの内積

38

In [96]:
#行列の積
a=np.array([[0,1,2],[3,4,5]])
b=np.array([[0,1],[2,3],[4,5]])

print(a.dot(b)) #行列の内積

[[10 13]
 [28 40]]


In [104]:
#行列の演算
a=np.array([0,6,3,-2,7,2,0,0,3])
a=a.reshape(3,3)
print(a) #3x3行列を作成

#転置行列
print(a.T)

#行列式
print(np.linalg.det(a))

#逆行列
print(np.linalg.inv(a))

[[ 0  6  3]
 [-2  7  2]
 [ 0  0  3]]
[[ 0 -2  0]
 [ 6  7  0]
 [ 3  2  3]]
36.0
[[ 0.58333333 -0.5        -0.25      ]
 [ 0.16666667  0.         -0.16666667]
 [ 0.          0.          0.33333333]]


In [111]:
np.linalg.inv(a).dot(a)

array([[  1.00000000e+00,  -4.44089210e-16,  -2.22044605e-16],
       [  0.00000000e+00,   1.00000000e+00,   2.77555756e-17],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00]])

In [13]:
#特定の行を消す

#numpy.delete(arr, obj, axis=None)
#arr: 入力配列
#obj: 消去する行番号や列番号をslice, int, リスト（配列）で指定
#axis: 消去対象となる軸（次元）
    
a=np.array([0,6,3,-2,7,2,0,0,3])
a=a.reshape(3,3)
print(a) #3x3行列を作成

new = np.delete(a, obj=0, axis=0)
print(new)



[[ 0  6  3]
 [-2  7  2]
 [ 0  0  3]]
[[-2  7  2]
 [ 0  0  3]]


In [2]:
import numpy as np
a=np.array([0,6,3,-2,7,2,0,0,3])
a=a.reshape(3,3)
print(a) #3x3行列を作成

[[ 0  6  3]
 [-2  7  2]
 [ 0  0  3]]
